spring:
  application:
    name: TuitionToAll-V2

  datasource:
    url: jdbc:mysql://localhost:3306/tuitiontoall_v2_test?createDatabaseIfNotExist=true
    username: root
    password: 123456

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
