spring:
  application:
    name: TuitionToAll-V2

  datasource:
    url: ${DB_URL}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PWD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB

file:
  upload-dir: uploads
  profile:
    pic-path: uploads/profiles/dp
    banner-path: uploads/profiles/banner