spring:
  application:
    name: TuitionToAll-V2

  profiles:
    active: ${SPRING_PROFILE}

  datasource:
    url: ${DB_URL}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PWD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
        hibernate:
            format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

file:
  upload-dir: uploads
  profile:
    pic-path: uploads/profiles/dp
    banner-path: uploads/profiles/banner
  course:
    thumbnail-path: uploads/courses/thumbnails

app:
  reset:
    frontend-reset-url: "http://localhost:4200/reset?token="