/*
 * Copyright (c) 2026 vinuth sri arampath
 *
 * This code is the intellectual property of vinuth sri arampath and is protected under copyright law.
 * Unauthorized copying, modification, distribution, or use of this code, in whole or in part,
 * without prior written permission is strictly prohibited.
 *
 * Portions of this code may be generated with AI and modified by vinuth sri arampath
 * All rights reserved.
 *
 *
 */

package edu.vinu.service.common.impl;

import edu.vinu.entity.BatchEntity;
import edu.vinu.entity.CourseEntity;
import edu.vinu.exception.custom.InvalidInputException;
import edu.vinu.model.Batch;
import edu.vinu.model.Course;
import edu.vinu.repository.BatchRepository;
import edu.vinu.request.BatchCreateRequest;
import edu.vinu.service.common.BatchService;
import edu.vinu.service.common.CourseService;
import lombok.RequiredArgsConstructor;
import org.modelmapper.ModelMapper;
import org.springframework.stereotype.Service;

import java.time.LocalDate;

@Service
@RequiredArgsConstructor
public class BatchServiceImpl implements BatchService {

    private final BatchRepository batchRepository;
    private final CourseService courseService;
    private final ModelMapper mapper;

    @Override
    public Batch createBatch(BatchCreateRequest request) {
        CourseEntity courseEntity = courseService.getCourseEntityById(request.getCourseId());
        if(isBatchStartDateValid(request.getStart_date())){
            if (!batchRepository.existsByNameAndCourseId(request.getName(),courseEntity.getId())){
                BatchEntity batchEntity=mapper.map(request, BatchEntity.class);
                batchEntity.setId(null); //prevent mapper to automatically inserts a new id for the batchEntity which is not required as it will be generated by the database
                batchEntity.setCourse(courseEntity);
                BatchEntity savedBatchEntity = batchRepository.save(batchEntity);
                Batch savedBatch = mapper.map(savedBatchEntity, Batch.class);
                savedBatch.setCourseId(courseEntity.getId());
                return savedBatch;
            }else{
                throw new InvalidInputException("Batch with the same name already exists for this courseEntity");
            }
        }else {
            throw new InvalidInputException("Start Date should be a future date");
        }
    }

    private Boolean isBatchStartDateValid(LocalDate date){
        return  date.isAfter(LocalDate.now());
    }
}
